name: stx_widgets_extensions
description: Provides some useful extensions for Widget class.
version: 0.0.1

homepage: https://github.com/VolodymyrSydorko/stx_widgets_extensions
documentation: https://github.com/VolodymyrSydorko/stx_widgets_extensions
repository: https://github.com/VolodymyrSydorko/stx_widgets_extensions

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true